name: Docker Image CI with Tag

on:
  push:
    branches:
      - master
    paths:
      - grafana_backup/**
      - Dockerfile    
      - DockerfileSlim
      - .github/workflows/docker-image.yml  
    tags:
      - '*'
  
jobs:
  push_to_registry:
    name: Push tagged docker image to GitHub Container Registry
    runs-on: gallis-gh-runner
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/grafana-backup-tool  
  
      - name: Extract metadata (tags, labels) for Docker (Slim version)
        id: meta_slim
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/grafana-backup-tool-slim
          flavor: |
            latest=auto
            suffix=-slim,onlatest=true

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image slim version
        uses: docker/build-push-action@v6
        with:
          file: ./DockerfileSlim
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta_slim.outputs.tags }}
          labels: ${{ steps.meta_slim.outputs.labels }}
